### ISSUE TITLE
[Bug]: Invalid file id

### ISSUE THREAD

**Issue by deLuXe83** [splewis/get5#1016]
### Documentation

- [X] I have looked in [the documentation](https://splewis.github.io/get5) and cannot find a solution to my problem.
- [X] I have searched [existing issues](https://github.com/splewis/get5/issues) and this bug has not been addressed.

### Get5 Version

14.3

### The Issue

Hi!
Veto System is working fine now.

But now we have the issue that - after voting workshop maps - we get the error
"invalid file id".
then when i change the map manually,
our cvars in the config file (eg. mp_maxrounds) are not getting executed.

any ideas?
thx!!
![Unbenannt2](https://user-images.githubusercontent.com/37928770/232162617-83deb354-1a1a-4ba4-aa77-8cad1ec86dda.PNG)

**Comment by nickdnk** [comment]
Please post your match config as instructed by the issue template.

**Comment by nickdnk** [comment]
I cannot reproduce this. My workshop maps load correctly after veto. Are you sure that map ID is correct? Match config would help.

**Comment by deLuXe83** [comment]
Hi
this is the config file

`"Match"
{
	"match_title"	"Match 1"
	"num_maps"		"2" // Must be an odd number or 2. 1->Bo1, 2->Bo2, 3->Bo3, etc.

	"spectators" // players allowed in spectator (e.g., admins) should go here
	{
		"players"
		{

		}
	}

	"skip_veto"		"0" // If set to 1, the maps will be preset using the first maps in the maplist below.

	"veto_first"	"random"  // Set to "team1" or "team2" to select who starts the veto. Any other values will default to team1 starting.
	"veto_mode"
	{	
	"team1_ban" ""
	"team2_ban" ""
	"team1_ban" ""
	"team2_ban" ""
	"team1_pick" ""
	"team2_pick" ""
	}

	"side_type"		"standard" // Either "standard", "always_knife", or "never_knife" 


	"maplist"
	{

		"fromfile"		"addons/sourcemod/configs/get5/turnier/mappool.cfg"	// Mappool

	}


	"players_per_team"		"4"
	"min_players_to_ready"		"2" // Minimum # of players a team must have to ready
	"min_spectators_to_ready"		"0" // How many spectators must be ready to begin.

	

	"team1"
	{
		"fromfile"		"addons/sourcemod/configs/get5/turnier/teamA.cfg"	// Team A
		// "fromfile"		"addons/sourcemod/configs/get5/turnier/teamB.cfg"	// Team B
		// "fromfile"		"addons/sourcemod/configs/get5/turnier/teamC.cfg"	// Team C
		// "fromfile"		"addons/sourcemod/configs/get5/turnier/teamD.cfg"	// Team D
	}

	"team2"
	{
		// "fromfile"		"addons/sourcemod/configs/get5/turnier/teamA.cfg"	// Team A
		"fromfile"		"addons/sourcemod/configs/get5/turnier/teamB.cfg"	// Team B
		// "fromfile"		"addons/sourcemod/configs/get5/turnier/teamC.cfg"	// Team C
		// "fromfile"		"addons/sourcemod/configs/get5/turnier/teamD.cfg"	// Team D
	}



	// These will be executed on each map start or config load.
	// You should not use this as a replacement for the cfg/get5/live.cfg config.
	"cvars"
	{
		"mp_maxrounds"				"20"
		"mp_overtime_enable"		"0"
		"mp_match_can_clinch"		"0" // 0 = No mercy rule, 1 = team can clinch match win early if they win > 1/2 total rounds
		"mp_match_restart_delay" "30"						// legt fest, wie lange pause nach der map
		"get5_auto_ready_active_players" "1"				// danach dann auto ready
		//"mp_roundtime"				"1.82"					// Für 4v4 Rundenzeit verringern
		//"mp_roundtime_hostage"		"1.82"					// Für 4v4 Rundenzeit verringern
		//"mp_roundtime_defuse"		"1.82"					// Für 4v4 Rundenzeit verringern

`

mappool.cfg: 

`

"maplist"
	{

"workshop/1984383383/de_basalt" "" 			// Basalt
"workshop/2459189885/de_marca" "" 		// Marca
"workshop/726359167/de_shipped" ""			// Shipped
"workshop/632040311/de_lite" ""			// Lite
"workshop/1982602598/de_swamp" ""		// Swamp
"workshop/215971897/de_coldwater" ""	// Coldwater
"workshop/2458920550/de_tuscan" "" 		// Tuscan NEU
	
	}

`

Thank you!

**Comment by deLuXe83** [comment]
It might be an issue with „de_marca“… because we have multiple versions of this map all named „de_marca“ but with different workshop ids…

**Comment by deLuXe83** [comment]
do you think reason could be we are using „de_tuscan“ from workshop?

because when i manually change the map via console „map de_tuscan“, the normal de_tuscan map appears…

**Comment by nickdnk** [comment]
I suspect this is because the ID is larger than a 32 bit integer for that map specifically, causing the current parser logic to overflow. I can fix this with https://www.sourcemod.net/new-api/string/StringToInt64.

**Comment by nickdnk** [comment]
Fixed in https://github.com/splewis/get5/releases/tag/v0.14.4.

**Comment by deLuXe83** [comment]
perfect thank you
i will give feedback as soon as i can test it

**Comment by deLuXe83** [comment]
Hi!
Now we finally could try the new update!

So the invalid file id error is gone - thanks for that!

But still, the CVARS (which are located in the lower part of the cfg file), are not loaded :(
Also then they are not added in the backup file.

Any ideas?
many thanks!

**Comment by nickdnk** [comment]
Post the exact, unedited match config you loaded as well as the backup files for that match. I have not heard anything about `cvars` not being written to backups.

**Comment by nickdnk** [comment]
If you refer to this:

> then when i change the map manually,
> our cvars in the config file (eg. mp_maxrounds) are not getting executed.

You should't manually change the map. The cvars are loaded when the match config is loaded and at various stages, such as when everyone is ready, before knife, before live etc.

**Comment by deLuXe83** [comment]
no, not when i change map manually,
this time when the normal match cfg is executed...

**Comment by nickdnk** [comment]
Please do this.

> Post the exact, unedited match config you loaded as well as the backup files for that match. I have not heard anything about `cvars` not being written to backups.
> 
> Remember to use 0.14.6 - there were 2 fixes since 0.14.4.

**Comment by deLuXe83** [comment]
hi, 
this is the cfg:

`"Match"
{
	"match_title"	"Match 2"
	"num_maps"		"2" // Must be an odd number or 2. 1->Bo1, 2->Bo2, 3->Bo3, etc.

	"spectators" // players allowed in spectator (e.g., admins) should go here
	{
		"players"
		{

		}
	}

	"skip_veto"		"0" // If set to 1, the maps will be preset using the first maps in the maplist below.

	"veto_first"	"random"  // Set to "team1" or "team2" to select who starts the veto. Any other values will default to team1 starting.
	"veto_mode"
	{	
	"team1_ban" ""
	"team2_ban" ""
	"team1_ban" ""
	"team2_ban" ""
	"team1_pick" ""
	"team2_pick" ""
	}
	
	"side_type"		"standard" // Either "standard", "always_knife", or "never_knife" 

	"maplist"
	{
		"fromfile"		"addons/sourcemod/configs/get5/turnier/mappool.cfg"	// Mappool


	}

	"players_per_team"		"4"
	"min_players_to_ready"		"2" // Minimum # of players a team must have to ready
	"min_spectators_to_ready"		"0" // How many spectators must be ready to begin.

	

	"team1"
	{
		// "fromfile"		"addons/sourcemod/configs/get5/turnier/teamA.cfg"	// Team A
		// "fromfile"		"addons/sourcemod/configs/get5/turnier/teamB.cfg"	// Team B
		"fromfile"		"addons/sourcemod/configs/get5/turnier/teamC.cfg"	// Team C
		// "fromfile"		"addons/sourcemod/configs/get5/turnier/teamD.cfg"	// Team D
	}

	"team2"
	{
		// "fromfile"		"addons/sourcemod/configs/get5/turnier/teamA.cfg"	// Team A
		// "fromfile"		"addons/sourcemod/configs/get5/turnier/teamB.cfg"	// Team B
		// "fromfile"		"addons/sourcemod/configs/get5/turnier/teamC.cfg"	// Team C
		"fromfile"		"addons/sourcemod/configs/get5/turnier/teamD.cfg"	// Team D
	}



	// These will be executed on each map start or config load.
	// You should not use this as a replacement for the cfg/get5/live.cfg config.
	"cvars"
	{
		"mp_maxrounds"				"20"
		"mp_overtime_enable"		"0"
		"mp_match_can_clinch"		"0" // 0 = No mercy rule, 1 = team can clinch match win early if they win > 1/2 total rounds
		"mp_match_restart_delay" "30"						// legt fest, wie lange pause nach der map
		"cash_team_loser_bonus" "1900"			// Loser Bonus startet mit 1900 (statt 1400)
		"mp_consecutive_loss_max" "3"			// Nach wievielen Runden maximaler Loser Bonus (Standard 4) => auf 3 geändert, weil mit 1900 gestartet wird
		
		//"mp_roundtime"				"1.82"					// Für 4v4 Rundenzeit verringern
		//"mp_roundtime_hostage"		"1.82"					// Für 4v4 Rundenzeit verringern
		//"mp_roundtime_defuse"		"1.82"					// Für 4v4 Rundenzeit verringern
	}
}`


and this one of the backup files

`"Backup"
{
	"timestamp"		"2023-05-05 21:42:47"
	"matchid"		"231"
	"gamestate"		"7"
	"team1_side"		"3"
	"team2_side"		"2"
	"team1_start_side"		"2"
	"team2_start_side"		"3"
	"team1_series_score"		"0"
	"team2_series_score"		"0"
	"series_draw"		"0"
	"team1_tac_pauses_used"		"0"
	"team2_tac_pauses_used"		"0"
	"team1_tech_pauses_used"		"0"
	"team2_tech_pauses_used"		"0"
	"team1_pause_time_used"		"0"
	"team2_pause_time_used"		"0"
	"mapnumber"		"0"
	"maps"
	{
		"de_ancient"		"1"
		"workshop__slash__580446503__slash__de_tulip"		"0"
	}
	"map_scores"
	{
		"0"
		{
			"team1"		"0"
			"team2"		"0"
		}
		"1"
		{
			"team1"		"0"
			"team2"		"0"
		}
	}
	"Match"
	{
		"matchid"		"231"
		"scrim"		"0"
		"skip_veto"		"0"
		"num_maps"		"2"
		"players_per_team"		"4"
		"coaches_per_team"		"2"
		"coaches_must_ready"		"0"
		"min_players_to_ready"		"2"
		"min_spectators_to_ready"		"0"
		"match_title"		"Match 2"
		"clinch_series"		"1"
		"wingman"		"0"
		"favored_percentage_team1"		"0"
		"side_type"		"standard"
		"maplist"
		{
			"de_ancient"		"__placeholder"
			"workshop__slash__580446503__slash__de_tulip"		"__placeholder"
			"workshop__slash__1982602598__slash__de_swamp"		"__placeholder"
			"de_vertigo"		"__placeholder"
			"workshop__slash__2664747046__slash__de_vara"		"__placeholder"
			"workshop__slash__123518981__slash__de_favela"		"__placeholder"
			"workshop__slash__727462766__slash__de_austria"		"__placeholder"
		}
		"team1"
		{
			"players"
			{
				"76561198018584388"		"__placeholder"
				"76561198073369697"		"__placeholder"
				"76561198136247666"		"__placeholder"
				"76561198013444801"		"__placeholder"
			}
			"name"		"TEAM_C"
			"tag"		"[C]"
			"flag"		"DE"
		}
		"team2"
		{
			"players"
			{
				"76561198847241077"		"__placeholder"
				"76561197963572337"		"__placeholder"
				"76561198069687775"		"__placeholder"
				"76561198358031700"		"__placeholder"
			}
			"name"		"TEAM_D"
			"tag"		"[D]"
			"flag"		"DE"
		}
		"spectators"
		{
			"name"		"casters"
		}
		"cvars"
		{
			"get5_web_api_key"		"__placeholder"
			"get5_web_api_url"		"__placeholder"
		}
	}
	"valve_backup"
	{
		"timestamp"		"2023-05-05 21:42:47"
		"team1"		"TEAM_D"
		"team2"		"TEAM_C"
		"map"		"de_ancient"
		"round"		"10"
		"FirstHalfScore"
		{
			"team1"		"6"
			"team2"		"4"
		}
		"History"
		{
			"NumConsecutiveTerroristLoses"		"2"
			"NumConsecutiveCTLoses"		"1"
			"LoserBonus"		"1900"
			"LoserMostRecentTeam"		"CT"
		}
		"RoundResults"
		{
			"round1"		"5"
			"round2"		"5"
			"round3"		"5"
			"round4"		"1"
			"round5"		"1"
			"round6"		"1"
			"round7"		"1"
			"round8"		"1"
			"round9"		"3"
			"round10"		"5"
			"round11"		"0"
			"round12"		"0"
			"round13"		"0"
			"round14"		"0"
			"round15"		"0"
			"round16"		"0"
			"round17"		"0"
			"round18"		"0"
			"round19"		"0"
			"round20"		"0"
			"round21"		"0"
			"round22"		"0"
			"round23"		"0"
			"round24"		"0"
			"round25"		"0"
			"round26"		"0"
			"round27"		"0"
			"round28"		"0"
			"round29"		"0"
			"round30"		"0"
		}
		"PlayersAliveT"
		{
			"round1"		"2"
			"round2"		"4"
			"round3"		"2"
			"round4"		"0"
			"round5"		"0"
			"round6"		"0"
			"round7"		"0"
			"round8"		"0"
			"round9"		"0"
			"round10"		"2"
			"round11"		"63"
			"round12"		"63"
			"round13"		"63"
			"round14"		"63"
			"round15"		"63"
			"round16"		"63"
			"round17"		"63"
			"round18"		"63"
			"round19"		"63"
			"round20"		"63"
			"round21"		"63"
			"round22"		"63"
			"round23"		"63"
			"round24"		"63"
			"round25"		"63"
			"round26"		"63"
			"round27"		"63"
			"round28"		"63"
			"round29"		"63"
			"round30"		"63"
		}
		"PlayersAliveCT"
		{
			"round1"		"0"
			"round2"		"0"
			"round3"		"0"
			"round4"		"2"
			"round5"		"4"
			"round6"		"4"
			"round7"		"3"
			"round8"		"3"
			"round9"		"2"
			"round10"		"0"
			"round11"		"63"
			"round12"		"63"
			"round13"		"63"
			"round14"		"63"
			"round15"		"63"
			"round16"		"63"
			"round17"		"63"
			"round18"		"63"
			"round19"		"63"
			"round20"		"63"
			"round21"		"63"
			"round22"		"63"
			"round23"		"63"
			"round24"		"63"
			"round25"		"63"
			"round26"		"63"
			"round27"		"63"
			"round28"		"63"
			"round29"		"63"
			"round30"		"63"
		}
		"Timeouts"
		{
			"team1"		"1"
			"team2"		"1"
			"technical"
			{
				"team1"		"0"
				"team2"		"0"
			}
		}
		"PlayersOnTeam1"
		{
			"886975349"
			{
				"name"		"floetenmann"
				"kills"		"6"
				"assists"		"1"
				"deaths"		"6"
				"mvps"		"2"
				"score"		"14"
				"cash"		"14400"
				"enemyKs"		"6"
				"enemyHSs"		"0"
				"enemy2Ks"		"3"
				"enemy3Ks"		"0"
				"enemy4Ks"		"0"
				"enemy5Ks"		"0"
				"enemyKAg"		"6"
				"enemyDamageDealt"		"0"
				"firstKs"		"0"
				"clutchKs"		"0"
				"kills_weapon_pistol"		"0"
				"kills_weapon_sniper"		"5"
				"roundsWon"		"6"
				"helmet"		"0"
				"MatchStats"
				{
					"EquipmentValue"
					{
						"round1"		"850"
						"round2"		"800"
						"round3"		"200"
						"round4"		"700"
						"round5"		"7650"
						"round6"		"7850"
						"round7"		"7850"
						"round8"		"8050"
						"round9"		"5950"
						"round10"		"8250"
					}
					"MoneySaved"
					{
						"round1"		"150"
						"round2"		"1950"
						"round3"		"3150"
						"round4"		"2750"
						"round5"		"2450"
						"round6"		"5200"
						"round7"		"8150"
						"round8"		"10400"
						"round9"		"12650"
						"round10"		"12500"
					}
					"LiveTime"
					{
						"round1"		"28"
						"round2"		"61"
						"round3"		"23"
						"round4"		"62"
						"round5"		"26"
						"round6"		"102"
						"round8"		"83"
						"round10"		"10"
					}
					"deaths"
					{
						"round1"		"1"
						"round2"		"1"
						"round3"		"1"
						"round4"		"1"
						"round8"		"1"
						"round10"		"1"
					}
					"CashEarned"
					{
						"round1"		"2550"
						"round2"		"3150"
						"round3"		"3450"
						"round4"		"5350"
						"round5"		"5900"
						"round6"		"8450"
						"round7"		"11600"
						"round8"		"13650"
						"round9"		"14750"
						"round10"		"14400"
					}
					"damage"
					{
						"round2"		"46"
						"round4"		"38"
						"round5"		"200"
						"round7"		"191"
						"round8"		"90"
						"round9"		"200"
					}
					"kills"
					{
						"round5"		"2"
						"round7"		"2"
						"round9"		"2"
					}
					"KillReward"
					{
						"round5"		"7650"
						"round7"		"7850"
						"round9"		"5950"
					}
					"UtilityDamage"
					{
						"round5"		"4"
						"round9"		"24"
					}
					"assists"
					{
						"round8"		"1"
					}
					"Totals"
					{
						"kills"		"6"
						"damage"		"765"
						"EquipmentValue"		"48150"
						"KillReward"		"800"
						"LiveTime"		"168"
						"deaths"		"6"
						"assists"		"1"
						"HeadshotKills"		"0"
						"objective"		"0"
						"CashEarned"		"31150"
						"UtilityDamage"		"28"
						"UtilityCount"		"3"
						"UtilitySuccesses"		"2"
						"UtilityEnemies"		"2"
						"FlashCount"		"1"
						"FlashSuccesses"		"0"
						"EnemiesFlashed"		"0"
						"1v1Count"		"0"
						"1v1Wins"		"0"
						"1v2Count"		"0"
						"1v2Wins"		"0"
						"EntryCount"		"3"
						"EntryWins"		"0"
					}
				}
				"WeaponPurchases"
				{
					"DefIndex_1"		"1"
					"DefIndex_3"		"1"
					"DefIndex_31"		"1"
					"DefIndex_43"		"1"
					"DefIndex_44"		"1"
					"DefIndex_45"		"1"
					"DefIndex_48"		"1"
					"DefIndex_50"		"1"
					"DefIndex_51"		"1"
					"DefIndex_55"		"1"
				}
				"ItemCooldown"
				{
					"heavyassaultsuit"		"-10"
				}
			}
			"109422047"
			{
				"name"		"komMando"
				"kills"		"16"
				"assists"		"0"
				"deaths"		"4"
				"mvps"		"3"
				"score"		"34"
				"cash"		"13450"
				"enemyKs"		"16"
				"enemyHSs"		"3"
				"enemy2Ks"		"2"
				"enemy3Ks"		"0"
				"enemy4Ks"		"2"
				"enemy5Ks"		"0"
				"enemyKAg"		"16"
				"enemyDamageDealt"		"44"
				"firstKs"		"4"
				"clutchKs"		"0"
				"kills_weapon_pistol"		"1"
				"kills_weapon_sniper"		"4"
				"roundsWon"		"6"
				"helmet"		"0"
				"MatchStats"
				{
					"EquipmentValue"
					{
						"round1"		"800"
						"round2"		"200"
						"round3"		"4800"
						"round4"		"1450"
						"round5"		"4750"
						"round6"		"6600"
						"round7"		"6600"
						"round8"		"8050"
						"round9"		"6600"
						"round10"		"6600"
					}
					"MoneySaved"
					{
						"round1"		"200"
						"round2"		"2600"
						"round3"		"100"
						"round4"		"2550"
						"round5"		"1850"
						"round6"		"1400"
						"round7"		"5200"
						"round8"		"7650"
						"round9"		"8000"
						"round10"		"11250"
					}
					"LiveTime"
					{
						"round1"		"26"
						"round2"		"24"
						"round3"		"97"
						"round4"		"36"
						"round5"		"26"
						"round6"		"102"
						"round7"		"28"
						"round8"		"63"
						"round10"		"55"
					}
					"deaths"
					{
						"round1"		"1"
						"round2"		"1"
						"round3"		"1"
						"round10"		"1"
					}
					"CashEarned"
					{
						"round1"		"2600"
						"round2"		"4700"
						"round3"		"3800"
						"round4"		"3900"
						"round5"		"5400"
						"round6"		"5850"
						"round7"		"8750"
						"round8"		"11300"
						"round9"		"12400"
						"round10"		"13450"
					}
					"kills"
					{
						"round3"		"1"
						"round4"		"1"
						"round5"		"2"
						"round6"		"4"
						"round7"		"1"
						"round8"		"4"
						"round9"		"2"
						"round10"		"1"
					}
					"damage"
					{
						"round3"		"100"
						"round4"		"98"
						"round5"		"200"
						"round6"		"389"
						"round7"		"100"
						"round8"		"310"
						"round9"		"156"
						"round10"		"44"
					}
					"KillReward"
					{
						"round3"		"4800"
						"round4"		"1450"
						"round5"		"4750"
						"round6"		"6600"
						"round7"		"6600"
						"round8"		"8050"
						"round9"		"6600"
						"round10"		"300"
					}
					"HeadshotKills"
					{
						"round4"		"1"
						"round6"		"1"
						"round9"		"1"
					}
					"objective"
					{
						"round9"		"1"
					}
					"Totals"
					{
						"kills"		"16"
						"damage"		"1397"
						"EquipmentValue"		"46450"
						"KillReward"		"4300"
						"LiveTime"		"137"
						"deaths"		"4"
						"assists"		"0"
						"HeadshotKills"		"3"
						"objective"		"1"
						"CashEarned"		"34950"
						"UtilityDamage"		"0"
						"UtilityCount"		"0"
						"UtilitySuccesses"		"0"
						"UtilityEnemies"		"0"
						"FlashCount"		"1"
						"FlashSuccesses"		"0"
						"EnemiesFlashed"		"0"
						"1v1Count"		"0"
						"1v1Wins"		"0"
						"1v2Count"		"1"
						"1v2Wins"		"0"
						"EntryCount"		"5"
						"EntryWins"		"4"
					}
				}
				"WeaponPurchases"
				{
					"DefIndex_3"		"1"
					"DefIndex_8"		"1"
					"DefIndex_10"		"1"
					"DefIndex_34"		"1"
					"DefIndex_43"		"1"
					"DefIndex_44"		"1"
					"DefIndex_45"		"1"
					"DefIndex_48"		"1"
					"DefIndex_50"		"1"
					"DefIndex_51"		"1"
					"DefIndex_55"		"1"
				}
				"ItemCooldown"
				{
					"heavyassaultsuit"		"-10"
				}
			}
			"397765972"
			{
				"name"		"Kurz02"
				"kills"		"4"
				"assists"		"0"
				"deaths"		"6"
				"mvps"		"0"
				"score"		"8"
				"cash"		"7900"
				"enemyKs"		"4"
				"enemyHSs"		"0"
				"enemy2Ks"		"0"
				"enemy3Ks"		"0"
				"enemy4Ks"		"0"
				"enemy5Ks"		"0"
				"enemyKAg"		"4"
				"enemyDamageDealt"		"100"
				"firstKs"		"0"
				"clutchKs"		"1"
				"kills_weapon_pistol"		"1"
				"kills_weapon_sniper"		"0"
				"roundsWon"		"6"
				"helmet"		"0"
				"MatchStats"
				{
					"kills"
					{
						"round1"		"1"
						"round3"		"1"
						"round7"		"1"
						"round10"		"1"
					}
					"damage"
					{
						"round1"		"116"
						"round3"		"100"
						"round4"		"29"
						"round7"		"12"
						"round10"		"100"
					}
					"EquipmentValue"
					{
						"round1"		"200"
						"round2"		"200"
						"round3"		"4500"
						"round4"		"3100"
						"round5"		"4500"
						"round6"		"4900"
						"round7"		"5400"
						"round8"		"6200"
						"round9"		"6200"
						"round10"		"6800"
					}
					"MoneySaved"
					{
						"round1"		"800"
						"round2"		"2850"
						"round3"		"750"
						"round4"		"1550"
						"round5"		"500"
						"round6"		"3350"
						"round7"		"6100"
						"round8"		"9050"
						"round9"		"9000"
						"round10"		"5700"
					}
					"KillReward"
					{
						"round1"		"200"
						"round3"		"4500"
						"round7"		"5400"
						"round10"		"300"
					}
					"LiveTime"
					{
						"round1"		"45"
						"round2"		"30"
						"round3"		"57"
						"round4"		"77"
						"round5"		"26"
						"round6"		"102"
						"round7"		"28"
						"round9"		"16"
						"round10"		"21"
					}
					"deaths"
					{
						"round1"		"1"
						"round2"		"1"
						"round3"		"1"
						"round4"		"1"
						"round9"		"1"
						"round10"		"1"
					}
					"CashEarned"
					{
						"round1"		"2850"
						"round2"		"5050"
						"round3"		"4450"
						"round4"		"4800"
						"round5"		"3750"
						"round6"		"6600"
						"round7"		"9650"
						"round8"		"12300"
						"round9"		"12500"
						"round10"		"7900"
					}
					"Totals"
					{
						"kills"		"4"
						"damage"		"357"
						"EquipmentValue"		"42000"
						"KillReward"		"1200"
						"LiveTime"		"210"
						"deaths"		"6"
						"assists"		"0"
						"HeadshotKills"		"0"
						"objective"		"0"
						"CashEarned"		"31550"
						"UtilityDamage"		"0"
						"UtilityCount"		"1"
						"UtilitySuccesses"		"0"
						"UtilityEnemies"		"0"
						"FlashCount"		"0"
						"FlashSuccesses"		"0"
						"EnemiesFlashed"		"0"
						"1v1Count"		"0"
						"1v1Wins"		"0"
						"1v2Count"		"1"
						"1v2Wins"		"0"
						"EntryCount"		"1"
						"EntryWins"		"0"
					}
				}
				"WeaponPurchases"
				{
					"DefIndex_1"		"1"
					"DefIndex_8"		"1"
					"DefIndex_43"		"1"
					"DefIndex_44"		"1"
					"DefIndex_45"		"1"
					"DefIndex_48"		"1"
					"DefIndex_50"		"1"
					"DefIndex_51"		"1"
					"DefIndex_55"		"1"
					"DefIndex_60"		"1"
				}
				"ItemCooldown"
				{
					"heavyassaultsuit"		"-10"
				}
			}
			"3306609"
			{
				"name"		"sChmierLapp"
				"kills"		"4"
				"assists"		"3"
				"deaths"		"6"
				"mvps"		"1"
				"score"		"11"
				"cash"		"7850"
				"enemyKs"		"4"
				"enemyHSs"		"2"
				"enemy2Ks"		"0"
				"enemy3Ks"		"1"
				"enemy4Ks"		"0"
				"enemy5Ks"		"0"
				"enemyKAg"		"4"
				"enemyDamageDealt"		"78"
				"firstKs"		"0"
				"clutchKs"		"0"
				"kills_weapon_pistol"		"1"
				"kills_weapon_sniper"		"0"
				"roundsWon"		"6"
				"helmet"		"0"
				"MatchStats"
				{
					"kills"
					{
						"round1"		"1"
						"round4"		"3"
					}
					"damage"
					{
						"round1"		"142"
						"round2"		"7"
						"round3"		"63"
						"round4"		"235"
						"round7"		"97"
						"round9"		"44"
						"round10"		"78"
					}
					"EquipmentValue"
					{
						"round1"		"850"
						"round2"		"200"
						"round3"		"5100"
						"round4"		"200"
						"round5"		"5500"
						"round6"		"5900"
						"round7"		"5900"
						"round8"		"6100"
						"round9"		"6100"
						"round10"		"6600"
					}
					"MoneySaved"
					{
						"round1"		"150"
						"round2"		"2850"
						"round3"		"350"
						"round4"		"3750"
						"round5"		"3150"
						"round6"		"5500"
						"round7"		"8450"
						"round8"		"5800"
						"round9"		"9050"
						"round10"		"5950"
					}
					"KillReward"
					{
						"round1"		"850"
						"round4"		"200"
					}
					"LiveTime"
					{
						"round1"		"54"
						"round2"		"23"
						"round3"		"102"
						"round4"		"36"
						"round5"		"26"
						"round7"		"116"
						"round9"		"27"
						"round10"		"54"
					}
					"deaths"
					{
						"round1"		"1"
						"round2"		"1"
						"round3"		"1"
						"round7"		"1"
						"round9"		"1"
						"round10"		"1"
					}
					"HeadshotKills"
					{
						"round1"		"1"
						"round4"		"1"
					}
					"CashEarned"
					{
						"round1"		"2850"
						"round2"		"5250"
						"round3"		"3750"
						"round4"		"4350"
						"round5"		"6400"
						"round6"		"8750"
						"round7"		"11700"
						"round8"		"9050"
						"round9"		"12550"
						"round10"		"7850"
					}
					"UtilityDamage"
					{
						"round4"		"12"
						"round7"		"27"
						"round10"		"32"
					}
					"EnemiesFlashed"
					{
						"round4"		"1"
					}
					"assists"
					{
						"round7"		"1"
						"round9"		"1"
						"round10"		"1"
					}
					"Totals"
					{
						"kills"		"4"
						"damage"		"666"
						"EquipmentValue"		"42450"
						"KillReward"		"1200"
						"LiveTime"		"283"
						"deaths"		"6"
						"assists"		"3"
						"HeadshotKills"		"2"
						"objective"		"0"
						"CashEarned"		"31550"
						"UtilityDamage"		"71"
						"UtilityCount"		"3"
						"UtilitySuccesses"		"3"
						"UtilityEnemies"		"5"
						"FlashCount"		"2"
						"FlashSuccesses"		"1"
						"EnemiesFlashed"		"1"
						"1v1Count"		"0"
						"1v1Wins"		"0"
						"1v2Count"		"1"
						"1v2Wins"		"0"
						"EntryCount"		"1"
						"EntryWins"		"0"
					}
				}
				"WeaponPurchases"
				{
					"DefIndex_1"		"1"
					"DefIndex_3"		"1"
					"DefIndex_10"		"1"
					"DefIndex_16"		"1"
					"DefIndex_43"		"1"
					"DefIndex_44"		"1"
					"DefIndex_45"		"1"
					"DefIndex_48"		"1"
					"DefIndex_50"		"1"
					"DefIndex_51"		"1"
					"DefIndex_55"		"1"
				}
				"ItemCooldown"
				{
					"heavyassaultsuit"		"-10"
				}
			}
		}
		"PlayersOnTeam2"
		{
			"175981938"
			{
				"name"		"lilKant"
				"kills"		"6"
				"assists"		"1"
				"deaths"		"7"
				"mvps"		"2"
				"score"		"13"
				"cash"		"3250"
				"enemyKs"		"6"
				"enemyHSs"		"3"
				"enemy2Ks"		"1"
				"enemy3Ks"		"1"
				"enemy4Ks"		"0"
				"enemy5Ks"		"0"
				"enemyKAg"		"6"
				"enemyDamageDealt"		"26"
				"firstKs"		"2"
				"clutchKs"		"0"
				"kills_weapon_pistol"		"1"
				"kills_weapon_sniper"		"0"
				"roundsWon"		"4"
				"helmet"		"0"
				"MatchStats"
				{
					"kills"
					{
						"round1"		"1"
						"round2"		"2"
						"round3"		"3"
					}
					"damage"
					{
						"round1"		"125"
						"round2"		"200"
						"round3"		"300"
						"round4"		"27"
						"round5"		"68"
						"round7"		"66"
						"round9"		"28"
						"round10"		"26"
					}
					"EquipmentValue"
					{
						"round1"		"850"
						"round2"		"4400"
						"round3"		"5100"
						"round4"		"5100"
						"round5"		"4700"
						"round6"		"200"
						"round7"		"4700"
						"round8"		"2750"
						"round9"		"4600"
						"round10"		"4400"
					}
					"MoneySaved"
					{
						"round1"		"150"
						"round2"		"150"
						"round3"		"2150"
						"round4"		"5350"
						"round5"		"50"
						"round6"		"2450"
						"round7"		"150"
						"round8"		"1000"
					}
					"KillReward"
					{
						"round1"		"850"
						"round2"		"4400"
						"round3"		"5100"
					}
					"LiveTime"
					{
						"round1"		"68"
						"round2"		"64"
						"round4"		"58"
						"round5"		"12"
						"round6"		"19"
						"round7"		"78"
						"round8"		"13"
						"round9"		"42"
						"round10"		"18"
					}
					"assists"
					{
						"round1"		"1"
					}
					"HeadshotKills"
					{
						"round1"		"1"
						"round2"		"2"
					}
					"CashEarned"
					{
						"round1"		"3700"
						"round2"		"4000"
						"round3"		"6300"
						"round4"		"7250"
						"round5"		"2450"
						"round6"		"4650"
						"round7"		"3550"
						"round8"		"4400"
						"round9"		"4200"
						"round10"		"3250"
					}
					"EnemiesFlashed"
					{
						"round2"		"2"
						"round7"		"1"
					}
					"deaths"
					{
						"round4"		"1"
						"round5"		"1"
						"round6"		"1"
						"round7"		"1"
						"round8"		"1"
						"round9"		"1"
						"round10"		"1"
					}
					"UtilityDamage"
					{
						"round9"		"28"
					}
					"Totals"
					{
						"kills"		"6"
						"damage"		"840"
						"EquipmentValue"		"36800"
						"KillReward"		"1800"
						"LiveTime"		"240"
						"deaths"		"7"
						"assists"		"1"
						"HeadshotKills"		"3"
						"objective"		"0"
						"CashEarned"		"33000"
						"UtilityDamage"		"28"
						"UtilityCount"		"4"
						"UtilitySuccesses"		"1"
						"UtilityEnemies"		"1"
						"FlashCount"		"4"
						"FlashSuccesses"		"2"
						"EnemiesFlashed"		"3"
						"1v1Count"		"0"
						"1v1Wins"		"0"
						"1v2Count"		"1"
						"1v2Wins"		"0"
						"EntryCount"		"4"
						"EntryWins"		"2"
					}
				}
				"WeaponPurchases"
				{
					"DefIndex_1"		"1"
					"DefIndex_7"		"1"
					"DefIndex_17"		"1"
					"DefIndex_43"		"1"
					"DefIndex_44"		"1"
					"DefIndex_45"		"1"
					"DefIndex_46"		"1"
					"DefIndex_50"		"1"
					"DefIndex_51"		"1"
				}
				"ItemCooldown"
				{
					"heavyassaultsuit"		"-10"
				}
			}
			"58318660"
			{
				"name"		"FoxJoschi"
				"kills"		"10"
				"assists"		"2"
				"deaths"		"7"
				"mvps"		"2"
				"score"		"29"
				"cash"		"5150"
				"enemyKs"		"10"
				"enemyHSs"		"3"
				"enemy2Ks"		"2"
				"enemy3Ks"		"1"
				"enemy4Ks"		"0"
				"enemy5Ks"		"0"
				"enemyKAg"		"10"
				"enemyDamageDealt"		"182"
				"firstKs"		"3"
				"clutchKs"		"1"
				"kills_weapon_pistol"		"4"
				"kills_weapon_sniper"		"3"
				"roundsWon"		"4"
				"helmet"		"0"
				"items"
				{
					"item"		"weapon_knife_t"
					"item"		"weapon_flashbang"
					"item"		"weapon_taser"
				}
				"MatchStats"
				{
					"kills"
					{
						"round1"		"2"
						"round2"		"2"
						"round4"		"1"
						"round8"		"1"
						"round9"		"1"
						"round10"		"3"
					}
					"damage"
					{
						"round1"		"213"
						"round2"		"200"
						"round3"		"93"
						"round4"		"142"
						"round8"		"100"
						"round9"		"123"
						"round10"		"182"
					}
					"EquipmentValue"
					{
						"round1"		"850"
						"round2"		"3900"
						"round3"		"5600"
						"round4"		"6250"
						"round5"		"3900"
						"round6"		"700"
						"round7"		"6250"
						"round8"		"1550"
						"round9"		"6050"
						"round10"		"3700"
					}
					"MoneySaved"
					{
						"round1"		"150"
						"round2"		"600"
						"round3"		"3250"
						"round4"		"50"
						"round5"		"1050"
						"round6"		"3450"
						"round7"		"100"
						"round8"		"2150"
						"round9"		"100"
						"round10"		"1000"
					}
					"KillReward"
					{
						"round1"		"850"
						"round2"		"3900"
						"round4"		"6250"
						"round8"		"1550"
						"round9"		"6050"
						"round10"		"900"
					}
					"LiveTime"
					{
						"round1"		"68"
						"round3"		"42"
						"round4"		"44"
						"round5"		"26"
						"round6"		"19"
						"round7"		"68"
						"round8"		"21"
						"round9"		"45"
					}
					"HeadshotKills"
					{
						"round1"		"1"
						"round10"		"2"
					}
					"objective"
					{
						"round1"		"1"
						"round9"		"1"
					}
					"CashEarned"
					{
						"round1"		"4300"
						"round2"		"3950"
						"round3"		"6300"
						"round4"		"2050"
						"round5"		"3450"
						"round6"		"6350"
						"round7"		"3500"
						"round8"		"6150"
						"round9"		"4700"
						"round10"		"5150"
					}
					"deaths"
					{
						"round3"		"1"
						"round4"		"1"
						"round5"		"1"
						"round6"		"1"
						"round7"		"1"
						"round8"		"1"
						"round9"		"1"
					}
					"assists"
					{
						"round3"		"1"
						"round4"		"1"
					}
					"Totals"
					{
						"kills"		"10"
						"damage"		"1053"
						"EquipmentValue"		"38750"
						"KillReward"		"2900"
						"LiveTime"		"265"
						"deaths"		"7"
						"assists"		"2"
						"HeadshotKills"		"3"
						"objective"		"0"
						"CashEarned"		"34700"
						"UtilityDamage"		"0"
						"UtilityCount"		"0"
						"UtilitySuccesses"		"0"
						"UtilityEnemies"		"0"
						"FlashCount"		"1"
						"FlashSuccesses"		"0"
						"EnemiesFlashed"		"0"
						"1v1Count"		"0"
						"1v1Wins"		"0"
						"1v2Count"		"0"
						"1v2Wins"		"0"
						"EntryCount"		"4"
						"EntryWins"		"3"
					}
				}
				"WeaponPurchases"
				{
					"DefIndex_7"		"1"
					"DefIndex_9"		"1"
					"DefIndex_17"		"1"
					"DefIndex_30"		"1"
					"DefIndex_36"		"1"
					"DefIndex_40"		"1"
					"DefIndex_43"		"1"
					"DefIndex_44"		"1"
					"DefIndex_45"		"1"
					"DefIndex_46"		"1"
					"DefIndex_50"		"1"
					"DefIndex_51"		"1"
				}
				"ItemCooldown"
				{
					"heavyassaultsuit"		"-10"
				}
			}
			"53179073"
			{
				"name"		"eXecutoR"
				"kills"		"2"
				"assists"		"0"
				"deaths"		"8"
				"mvps"		"0"
				"score"		"6"
				"cash"		"4200"
				"enemyKs"		"2"
				"enemyHSs"		"1"
				"enemy2Ks"		"0"
				"enemy3Ks"		"0"
				"enemy4Ks"		"0"
				"enemy5Ks"		"0"
				"enemyKAg"		"2"
				"enemyDamageDealt"		"8"
				"firstKs"		"0"
				"clutchKs"		"1"
				"kills_weapon_pistol"		"0"
				"kills_weapon_sniper"		"0"
				"roundsWon"		"4"
				"helmet"		"0"
				"items"
				{
					"item"		"weapon_knife_survival_bowie"
					"item"		"weapon_glock"
					"item"		"weapon_ak47"
				}
				"MatchStats"
				{
					"damage"
					{
						"round1"		"11"
						"round5"		"27"
						"round7"		"100"
						"round9"		"169"
						"round10"		"8"
					}
					"EquipmentValue"
					{
						"round1"		"900"
						"round2"		"3550"
						"round3"		"4300"
						"round4"		"4200"
						"round5"		"4150"
						"round6"		"700"
						"round7"		"4750"
						"round8"		"1550"
						"round9"		"4900"
						"round10"		"4900"
					}
					"MoneySaved"
					{
						"round1"		"100"
						"round3"		"3050"
						"round4"		"2100"
						"round5"		"50"
						"round6"		"1750"
						"round7"		"100"
						"round8"		"2450"
						"round9"		"1150"
						"round10"		"950"
					}
					"LiveTime"
					{
						"round1"		"112"
						"round3"		"29"
						"round4"		"39"
						"round5"		"23"
						"round6"		"19"
						"round7"		"95"
						"round8"		"15"
						"round9"		"43"
					}
					"deaths"
					{
						"round1"		"1"
						"round3"		"1"
						"round4"		"1"
						"round5"		"1"
						"round6"		"1"
						"round7"		"1"
						"round8"		"1"
						"round9"		"1"
					}
					"CashEarned"
					{
						"round1"		"3350"
						"round2"		"3550"
						"round3"		"6300"
						"round4"		"4000"
						"round5"		"2450"
						"round6"		"4650"
						"round7"		"3800"
						"round8"		"5850"
						"round9"		"5650"
						"round10"		"4200"
					}
					"objective"
					{
						"round2"		"1"
					}
					"kills"
					{
						"round7"		"1"
						"round9"		"1"
					}
					"KillReward"
					{
						"round7"		"4750"
						"round9"		"4900"
					}
					"HeadshotKills"
					{
						"round7"		"1"
					}
					"UtilityDamage"
					{
						"round9"		"3"
						"round10"		"8"
					}
					"Totals"
					{
						"kills"		"2"
						"damage"		"315"
						"EquipmentValue"		"33900"
						"KillReward"		"600"
						"LiveTime"		"307"
						"deaths"		"8"
						"assists"		"0"
						"HeadshotKills"		"1"
						"objective"		"0"
						"CashEarned"		"32100"
						"UtilityDamage"		"11"
						"UtilityCount"		"3"
						"UtilitySuccesses"		"2"
						"UtilityEnemies"		"2"
						"FlashCount"		"2"
						"FlashSuccesses"		"0"
						"EnemiesFlashed"		"0"
						"1v1Count"		"0"
						"1v1Wins"		"0"
						"1v2Count"		"0"
						"1v2Wins"		"0"
						"EntryCount"		"0"
						"EntryWins"		"0"
					}
				}
				"WeaponPurchases"
				{
					"DefIndex_1"		"1"
					"DefIndex_7"		"1"
					"DefIndex_13"		"1"
					"DefIndex_17"		"1"
					"DefIndex_30"		"1"
					"DefIndex_40"		"1"
					"DefIndex_43"		"1"
					"DefIndex_44"		"1"
					"DefIndex_45"		"1"
					"DefIndex_47"		"1"
					"DefIndex_50"		"1"
					"DefIndex_51"		"1"
				}
				"ItemCooldown"
				{
					"heavyassaultsuit"		"-10"
				}
			}
			"113103969"
			{
				"name"		"marF"
				"kills"		"4"
				"assists"		"1"
				"deaths"		"8"
				"mvps"		"0"
				"score"		"14"
				"cash"		"4250"
				"enemyKs"		"4"
				"enemyHSs"		"1"
				"enemy2Ks"		"0"
				"enemy3Ks"		"0"
				"enemy4Ks"		"0"
				"enemy5Ks"		"0"
				"enemyKAg"		"4"
				"enemyDamageDealt"		"181"
				"firstKs"		"1"
				"clutchKs"		"0"
				"kills_weapon_pistol"		"1"
				"kills_weapon_sniper"		"0"
				"roundsWon"		"4"
				"helmet"		"0"
				"MatchStats"
				{
					"kills"
					{
						"round1"		"1"
						"round3"		"1"
						"round4"		"1"
						"round10"		"1"
					}
					"damage"
					{
						"round1"		"51"
						"round3"		"7"
						"round4"		"58"
						"round8"		"16"
						"round9"		"66"
						"round10"		"181"
					}
					"EquipmentValue"
					{
						"round1"		"800"
						"round2"		"3500"
						"round3"		"4200"
						"round4"		"5300"
						"round5"		"5100"
						"round6"		"700"
						"round7"		"5100"
						"round8"		"3450"
						"round9"		"4700"
						"round10"		"5100"
					}
					"KillReward"
					{
						"round1"		"800"
						"round3"		"4200"
						"round4"		"5300"
						"round10"		"300"
					}
					"LiveTime"
					{
						"round1"		"105"
						"round2"		"64"
						"round4"		"44"
						"round5"		"29"
						"round6"		"15"
						"round7"		"76"
						"round8"		"17"
						"round9"		"48"
						"round10"		"48"
					}
					"deaths"
					{
						"round1"		"1"
						"round4"		"1"
						"round5"		"1"
						"round6"		"1"
						"round7"		"1"
						"round8"		"1"
						"round9"		"1"
						"round10"		"1"
					}
					"CashEarned"
					{
						"round1"		"3550"
						"round2"		"3500"
						"round3"		"6650"
						"round4"		"8150"
						"round5"		"5650"
						"round6"		"6950"
						"round7"		"5450"
						"round8"		"5600"
						"round9"		"5300"
						"round10"		"4250"
					}
					"EnemiesFlashed"
					{
						"round1"		"2"
						"round6"		"1"
						"round10"		"1"
					}
					"MoneySaved"
					{
						"round2"		"250"
						"round3"		"2800"
						"round4"		"5950"
						"round5"		"3250"
						"round6"		"4250"
						"round7"		"2050"
						"round8"		"2200"
						"round9"		"1100"
						"round10"		"400"
					}
					"objective"
					{
						"round3"		"1"
						"round10"		"1"
					}
					"UtilityDamage"
					{
						"round9"		"12"
					}
					"assists"
					{
						"round10"		"1"
					}
					"HeadshotKills"
					{
						"round10"		"1"
					}
					"Totals"
					{
						"kills"		"4"
						"damage"		"379"
						"EquipmentValue"		"37950"
						"KillReward"		"1200"
						"LiveTime"		"314"
						"deaths"		"8"
						"assists"		"1"
						"HeadshotKills"		"1"
						"objective"		"0"
						"CashEarned"		"33000"
						"UtilityDamage"		"12"
						"UtilityCount"		"2"
						"UtilitySuccesses"		"1"
						"UtilityEnemies"		"1"
						"FlashCount"		"4"
						"FlashSuccesses"		"3"
						"EnemiesFlashed"		"4"
						"1v1Count"		"0"
						"1v1Wins"		"0"
						"1v2Count"		"1"
						"1v2Wins"		"0"
						"EntryCount"		"2"
						"EntryWins"		"1"
					}
				}
				"WeaponPurchases"
				{
					"DefIndex_1"		"1"
					"DefIndex_7"		"1"
					"DefIndex_13"		"1"
					"DefIndex_17"		"1"
					"DefIndex_36"		"1"
					"DefIndex_43"		"1"
					"DefIndex_44"		"1"
					"DefIndex_45"		"1"
					"DefIndex_46"		"1"
					"DefIndex_51"		"1"
				}
				"ItemCooldown"
				{
					"heavyassaultsuit"		"-10"
				}
			}
		}
	}
	"Stats"
	{
		"series_type"		"bo2"
		"team1"
		{
			"name"		"TEAM_C"
		}
		"team2"
		{
			"name"		"TEAM_D"
		}
		"map0"
		{
			"demo_filename"		"2023-05-05_21_231_map1_de_ancient.dem"
			"team1"
			{
				"players"
				{
					"76561198136247666"
					{
						"name"		"lil Kant"
						"coaching"		"0"
						"kills"		"6"
						"deaths"		"7"
						"assists"		"1"
						"flashbang_assists"		"0"
						"teamkills"		"0"
						"suicides"		"0"
						"damage"		"840"
						"util_damage"		"28"
						"enemies_flashed"		"0"
						"friendlies_flashed"		"3"
						"knife_kills"		"0"
						"headshot_kills"		"3"
						"roundsplayed"		"10"
						"bomb_defuses"		"0"
						"bomb_plants"		"0"
						"1kill_rounds"		"1"
						"2kill_rounds"		"1"
						"3kill_rounds"		"1"
						"4kill_rounds"		"0"
						"5kill_rounds"		"0"
						"v1"		"0"
						"v2"		"0"
						"v3"		"0"
						"v4"		"0"
						"v5"		"0"
						"firstkill_t"		"2"
						"firstkill_ct"		"0"
						"firstdeath_t"		"2"
						"firstdeath_ct"		"0"
						"tradekill"		"0"
						"kast"		"3"
						"contribution_score"		"13"
						"mvp"		"2"
						"init"		"1"
					}
					"76561198018584388"
					{
						"name"		"FoxJoschi"
						"coaching"		"0"
						"kills"		"10"
						"deaths"		"7"
						"assists"		"2"
						"flashbang_assists"		"0"
						"teamkills"		"0"
						"suicides"		"0"
						"damage"		"1053"
						"util_damage"		"0"
						"enemies_flashed"		"0"
						"friendlies_flashed"		"0"
						"knife_kills"		"0"
						"headshot_kills"		"3"
						"roundsplayed"		"10"
						"bomb_defuses"		"0"
						"bomb_plants"		"2"
						"1kill_rounds"		"3"
						"2kill_rounds"		"2"
						"3kill_rounds"		"1"
						"4kill_rounds"		"0"
						"5kill_rounds"		"0"
						"v1"		"0"
						"v2"		"0"
						"v3"		"0"
						"v4"		"0"
						"v5"		"0"
						"firstkill_t"		"3"
						"firstkill_ct"		"0"
						"firstdeath_t"		"1"
						"firstdeath_ct"		"0"
						"tradekill"		"0"
						"kast"		"7"
						"contribution_score"		"29"
						"mvp"		"2"
						"init"		"1"
					}
					"76561198013444801"
					{
						"name"		"✘ eXecutoR^ ✘"
						"coaching"		"0"
						"kills"		"2"
						"deaths"		"8"
						"assists"		"0"
						"flashbang_assists"		"0"
						"teamkills"		"0"
						"suicides"		"0"
						"damage"		"315"
						"util_damage"		"11"
						"enemies_flashed"		"0"
						"friendlies_flashed"		"0"
						"knife_kills"		"0"
						"headshot_kills"		"1"
						"roundsplayed"		"10"
						"bomb_defuses"		"0"
						"bomb_plants"		"1"
						"1kill_rounds"		"2"
						"2kill_rounds"		"0"
						"3kill_rounds"		"0"
						"4kill_rounds"		"0"
						"5kill_rounds"		"0"
						"v1"		"0"
						"v2"		"0"
						"v3"		"0"
						"v4"		"0"
						"v5"		"0"
						"firstkill_t"		"0"
						"firstkill_ct"		"0"
						"firstdeath_t"		"0"
						"firstdeath_ct"		"0"
						"tradekill"		"0"
						"kast"		"4"
						"contribution_score"		"6"
						"mvp"		"0"
						"init"		"1"
					}
					"76561198073369697"
					{
						"name"		"marF"
						"coaching"		"0"
						"kills"		"4"
						"deaths"		"8"
						"assists"		"1"
						"flashbang_assists"		"0"
						"teamkills"		"0"
						"suicides"		"0"
						"damage"		"379"
						"util_damage"		"12"
						"enemies_flashed"		"2"
						"friendlies_flashed"		"3"
						"knife_kills"		"0"
						"headshot_kills"		"1"
						"roundsplayed"		"10"
						"bomb_defuses"		"0"
						"bomb_plants"		"2"
						"1kill_rounds"		"4"
						"2kill_rounds"		"0"
						"3kill_rounds"		"0"
						"4kill_rounds"		"0"
						"5kill_rounds"		"0"
						"v1"		"0"
						"v2"		"0"
						"v3"		"0"
						"v4"		"0"
						"v5"		"0"
						"firstkill_t"		"1"
						"firstkill_ct"		"0"
						"firstdeath_t"		"1"
						"firstdeath_ct"		"0"
						"tradekill"		"0"
						"kast"		"5"
						"contribution_score"		"14"
						"mvp"		"0"
						"init"		"1"
					}
				}
				"starting_side"		"2"
				"score"		"4"
				"score_t"		"4"
				"score_ct"		"0"
			}
			"team2"
			{
				"players"
				{
					"76561198847241077"
					{
						"name"		"floetenmann"
						"coaching"		"0"
						"kills"		"6"
						"deaths"		"6"
						"assists"		"1"
						"flashbang_assists"		"0"
						"teamkills"		"0"
						"suicides"		"0"
						"damage"		"765"
						"util_damage"		"28"
						"enemies_flashed"		"1"
						"friendlies_flashed"		"0"
						"knife_kills"		"0"
						"headshot_kills"		"0"
						"roundsplayed"		"10"
						"bomb_defuses"		"0"
						"bomb_plants"		"0"
						"1kill_rounds"		"0"
						"2kill_rounds"		"3"
						"3kill_rounds"		"0"
						"4kill_rounds"		"0"
						"5kill_rounds"		"0"
						"v1"		"0"
						"v2"		"0"
						"v3"		"0"
						"v4"		"0"
						"v5"		"0"
						"firstkill_t"		"0"
						"firstkill_ct"		"0"
						"firstdeath_t"		"0"
						"firstdeath_ct"		"3"
						"tradekill"		"0"
						"kast"		"5"
						"contribution_score"		"14"
						"mvp"		"2"
						"init"		"1"
					}
					"76561198069687775"
					{
						"name"		"komMando"
						"coaching"		"0"
						"kills"		"16"
						"deaths"		"4"
						"assists"		"0"
						"flashbang_assists"		"0"
						"teamkills"		"0"
						"suicides"		"0"
						"damage"		"1397"
						"util_damage"		"0"
						"enemies_flashed"		"0"
						"friendlies_flashed"		"0"
						"knife_kills"		"0"
						"headshot_kills"		"3"
						"roundsplayed"		"10"
						"bomb_defuses"		"1"
						"bomb_plants"		"0"
						"1kill_rounds"		"4"
						"2kill_rounds"		"2"
						"3kill_rounds"		"0"
						"4kill_rounds"		"2"
						"5kill_rounds"		"0"
						"v1"		"0"
						"v2"		"0"
						"v3"		"0"
						"v4"		"0"
						"v5"		"0"
						"firstkill_t"		"0"
						"firstkill_ct"		"4"
						"firstdeath_t"		"0"
						"firstdeath_ct"		"1"
						"tradekill"		"1"
						"kast"		"8"
						"contribution_score"		"34"
						"mvp"		"3"
						"init"		"1"
					}
					"76561198358031700"
					{
						"name"		"Kurz_02"
						"coaching"		"0"
						"kills"		"4"
						"deaths"		"6"
						"assists"		"0"
						"flashbang_assists"		"0"
						"teamkills"		"0"
						"suicides"		"0"
						"damage"		"357"
						"util_damage"		"0"
						"enemies_flashed"		"0"
						"friendlies_flashed"		"0"
						"knife_kills"		"0"
						"headshot_kills"		"0"
						"roundsplayed"		"10"
						"bomb_defuses"		"0"
						"bomb_plants"		"0"
						"1kill_rounds"		"4"
						"2kill_rounds"		"0"
						"3kill_rounds"		"0"
						"4kill_rounds"		"0"
						"5kill_rounds"		"0"
						"v1"		"0"
						"v2"		"0"
						"v3"		"0"
						"v4"		"0"
						"v5"		"0"
						"firstkill_t"		"0"
						"firstkill_ct"		"0"
						"firstdeath_t"		"0"
						"firstdeath_ct"		"1"
						"tradekill"		"0"
						"kast"		"7"
						"contribution_score"		"8"
						"mvp"		"0"
						"init"		"1"
					}
					"76561197963572337"
					{
						"name"		"sChmierLapp"
						"coaching"		"0"
						"kills"		"4"
						"deaths"		"6"
						"assists"		"3"
						"flashbang_assists"		"0"
						"teamkills"		"0"
						"suicides"		"0"
						"damage"		"666"
						"util_damage"		"71"
						"enemies_flashed"		"0"
						"friendlies_flashed"		"1"
						"knife_kills"		"0"
						"headshot_kills"		"2"
						"roundsplayed"		"10"
						"bomb_defuses"		"0"
						"bomb_plants"		"0"
						"1kill_rounds"		"1"
						"2kill_rounds"		"0"
						"3kill_rounds"		"1"
						"4kill_rounds"		"0"
						"5kill_rounds"		"0"
						"v1"		"0"
						"v2"		"0"
						"v3"		"0"
						"v4"		"0"
						"v5"		"0"
						"firstkill_t"		"0"
						"firstkill_ct"		"0"
						"firstdeath_t"		"0"
						"firstdeath_ct"		"1"
						"tradekill"		"0"
						"kast"		"8"
						"contribution_score"		"11"
						"mvp"		"1"
						"init"		"1"
					}
				}
				"starting_side"		"3"
				"score"		"6"
				"score_ct"		"6"
				"score_t"		"0"
			}
			"mapname"		"de_ancient"
		}
	}
}
`

**Comment by nickdnk** [comment]
I can't reproduce this. This match config works for me with 0.14.6 and generates this backup file:

## MATCH
```
"Match"
{
    "match_title" "Match 2"
    "num_maps" "2" // Must be an odd number or 2. 1->Bo1, 2->Bo2, 3->Bo3, etc.
    "spectators" // players allowed in spectator (e.g., admins) should go here
    {
        "players"
        {

        }
    }
    "skip_veto"		"0" // If set to 1, the maps will be preset using the first maps in the maplist below.
    "veto_first"	"random"  // Set to "team1" or "team2" to select who starts the veto. Any other values will default to team1 starting.
    "veto_mode"
    {
        "team1_ban" ""
        "team2_ban" ""
        "team1_ban" ""
        "team2_ban" ""
        "team1_pick" ""
        "team2_pick" ""
    }
    "side_type"		"standard" // Either "standard", "always_knife", or "never_knife"
    "maplist"
    {
        "de_dust2" ""
        "de_mirage" ""
    }
    "players_per_team"		"4"
    "min_players_to_ready"		"2" // Minimum # of players a team must have to ready
    "min_spectators_to_ready"		"0" // How many spectators must be ready to begin.
    "team1"
    {
        // "fromfile"		"addons/sourcemod/configs/get5/turnier/teamA.cfg"	// Team A
        // "fromfile"		"addons/sourcemod/configs/get5/turnier/teamB.cfg"	// Team B
        // "fromfile"		"addons/sourcemod/configs/get5/turnier/teamC.cfg"	// Team C
        // "fromfile"		"addons/sourcemod/configs/get5/turnier/teamD.cfg"	// Team D
        "players"
        {
            "76561199473694121" "asdasd"
        }
    }
    
    "team2"
    {
        // "fromfile"		"addons/sourcemod/configs/get5/turnier/teamA.cfg"	// Team A
        // "fromfile"		"addons/sourcemod/configs/get5/turnier/teamB.cfg"	// Team B
        // "fromfile"		"addons/sourcemod/configs/get5/turnier/teamC.cfg"	// Team C
        //"fromfile"		"addons/sourcemod/configs/get5/turnier/teamD.cfg"	// Team D
        "players"
        {
            "76561199473694129" "nyx2"
        }
    }
    // These will be executed on each map start or config load.
    // You should not use this as a replacement for the cfg/get5/live.cfg config.
    "cvars"
    {
        "mp_maxrounds"				"20"
        "mp_overtime_enable"		"0"
        "mp_match_can_clinch"		"0" // 0 = No mercy rule, 1 = team can clinch match win early if they win > 1/2 total rounds
        "mp_match_restart_delay" "30"						// legt fest, wie lange pause nach der map
        "cash_team_loser_bonus" "1900"			// Loser Bonus startet mit 1900 (statt 1400)
        "mp_consecutive_loss_max" "3"			// Nach wievielen Runden maximaler Loser Bonus (Standard 4) => auf 3 geändert, weil mit 1900 gestartet wird
        
        //"mp_roundtime"				"1.82"					// Für 4v4 Rundenzeit verringern
        //"mp_roundtime_hostage"		"1.82"					// Für 4v4 Rundenzeit verringern
        //"mp_roundtime_defuse"		"1.82"					// Für 4v4 Rundenzeit verringern
    }
}
```

## BACKUP
```
"Backup"
{
        "timestamp"             "2023-05-06 13:01:13"
        "gamestate"             "3"
        "team1_side"            "3"
        "team2_side"            "2"
        "team1_start_side"              "3"
        "team2_start_side"              "2"
        "team1_series_score"            "0"
        "team2_series_score"            "0"
        "series_draw"           "0"
        "team1_tac_pauses_used"         "0"
        "team2_tac_pauses_used"         "0"
        "team1_tech_pauses_used"                "0"
        "team2_tech_pauses_used"                "0"
        "team1_pause_time_used"         "0"
        "team2_pause_time_used"         "0"
        "mapnumber"             "0"
        "maps"
        {
                "de_dust2"              "2"
                "de_mirage"             "2"
        }
        "map_scores"
        {
                "0"
                {
                        "team1"         "0"
                        "team2"         "0"
                }
                "1"
                {
                        "team1"         "0"
                        "team2"         "0"
                }
        }
        "Match"
        {
                "scrim"         "0"
                "skip_veto"             "1"
                "num_maps"              "2"
                "players_per_team"              "4"
                "coaches_per_team"              "2"
                "coaches_must_ready"            "0"
                "min_players_to_ready"          "2"
                "min_spectators_to_ready"               "0"
                "match_title"           "Match 2"
                "clinch_series"         "1"
                "wingman"               "0"
                "favored_percentage_team1"              "0"
                "side_type"             "standard"
                "maplist"
                {
                        "de_dust2"              "__placeholder"
                        "de_mirage"             "__placeholder"
                }
                "team1"
                {
                        "players"
                        {
                                "76561199473694121"             "asdasd"
                        }
                }
                "team2"
                {
                        "players"
                        {
                                "76561199473694129"             "nyx2"
                        }
                }
                "spectators"
                {
                        "name"          "casters"
                }
                "cvars"
                {
                        "mp_maxrounds"          "20"
                        "mp_overtime_enable"            "0"
                        "mp_match_can_clinch"           "0"
                        "mp_match_restart_delay"                "30"
                        "cash_team_loser_bonus"         "1900"
                        "mp_consecutive_loss_max"               "3"
                }
        }
        "Stats"
        {
                "series_type"           "bo2"
                "team1"
                {
                }
                "team2"
                {
                }
        }
}

```

**Comment by nickdnk** [comment]
Also note that you cannot combine `veto_first: random` with `veto_mode`.

**Comment by deLuXe83** [comment]
> Also note that you cannot combine `veto_first` with `veto_mode`.

yes i know. unfortunately ;-)

**Comment by deLuXe83** [comment]
> I can't reproduce this. This match config works for me with 0.14.6 and generates this backup file:
> 
> ## MATCH
> ```
> "Match"
> {
>     "match_title" "Match 2"
>     "num_maps" "2" // Must be an odd number or 2. 1->Bo1, 2->Bo2, 3->Bo3, etc.
>     "spectators" // players allowed in spectator (e.g., admins) should go here
>     {
>         "players"
>         {
> 
>         }
>     }
>     "skip_veto"		"0" // If set to 1, the maps will be preset using the first maps in the maplist below.
>     "veto_first"	"random"  // Set to "team1" or "team2" to select who starts the veto. Any other values will default to team1 starting.
>     "veto_mode"
>     {
>         "team1_ban" ""
>         "team2_ban" ""
>         "team1_ban" ""
>         "team2_ban" ""
>         "team1_pick" ""
>         "team2_pick" ""
>     }
>     "side_type"		"standard" // Either "standard", "always_knife", or "never_knife"
>     "maplist"
>     {
>         "fromfile" "addons/sourcemod/maps.cfg"
>     }
>     "players_per_team"		"4"
>     "min_players_to_ready"		"2" // Minimum # of players a team must have to ready
>     "min_spectators_to_ready"		"0" // How many spectators must be ready to begin.
>     "team1"
>     {
>         // "fromfile"		"addons/sourcemod/configs/get5/turnier/teamA.cfg"	// Team A
>         // "fromfile"		"addons/sourcemod/configs/get5/turnier/teamB.cfg"	// Team B
>         // "fromfile"		"addons/sourcemod/configs/get5/turnier/teamC.cfg"	// Team C
>         "fromfile"		"addons/sourcemod/teamD.cfg"	// Team D
> 
>     }
>     
>     "team2"
>     {
>         // "fromfile"		"addons/sourcemod/configs/get5/turnier/teamA.cfg"	// Team A
>         // "fromfile"		"addons/sourcemod/configs/get5/turnier/teamB.cfg"	// Team B
>         // "fromfile"		"addons/sourcemod/configs/get5/turnier/teamC.cfg"	// Team C
>         //"fromfile"		"addons/sourcemod/configs/get5/turnier/teamD.cfg"	// Team D
>         "players"
>         {
>             "76561199473694129" "nyx2"
>         }
>     }
>     // These will be executed on each map start or config load.
>     // You should not use this as a replacement for the cfg/get5/live.cfg config.
>     "cvars"
>     {
>         "mp_maxrounds"				"20"
>         "mp_overtime_enable"		"0"
>         "mp_match_can_clinch"		"0" // 0 = No mercy rule, 1 = team can clinch match win early if they win > 1/2 total rounds
>         "mp_match_restart_delay" "30"						// legt fest, wie lange pause nach der map
>         "cash_team_loser_bonus" "1900"			// Loser Bonus startet mit 1900 (statt 1400)
>         "mp_consecutive_loss_max" "3"			// Nach wievielen Runden maximaler Loser Bonus (Standard 4) => auf 3 geändert, weil mit 1900 gestartet wird
>         
>         //"mp_roundtime"				"1.82"					// Für 4v4 Rundenzeit verringern
>         //"mp_roundtime_hostage"		"1.82"					// Für 4v4 Rundenzeit verringern
>         //"mp_roundtime_defuse"		"1.82"					// Für 4v4 Rundenzeit verringern
>     }
> }
> ```
> 
> ## BACKUP
> ```
> "Backup"
> {
>         "timestamp"             "2023-05-06 13:01:13"
>         "gamestate"             "3"
>         "team1_side"            "3"
>         "team2_side"            "2"
>         "team1_start_side"              "3"
>         "team2_start_side"              "2"
>         "team1_series_score"            "0"
>         "team2_series_score"            "0"
>         "series_draw"           "0"
>         "team1_tac_pauses_used"         "0"
>         "team2_tac_pauses_used"         "0"
>         "team1_tech_pauses_used"                "0"
>         "team2_tech_pauses_used"                "0"
>         "team1_pause_time_used"         "0"
>         "team2_pause_time_used"         "0"
>         "mapnumber"             "0"
>         "maps"
>         {
>                 "de_dust2"              "2"
>                 "de_mirage"             "2"
>         }
>         "map_scores"
>         {
>                 "0"
>                 {
>                         "team1"         "0"
>                         "team2"         "0"
>                 }
>                 "1"
>                 {
>                         "team1"         "0"
>                         "team2"         "0"
>                 }
>         }
>         "Match"
>         {
>                 "scrim"         "0"
>                 "skip_veto"             "1"
>                 "num_maps"              "2"
>                 "players_per_team"              "4"
>                 "coaches_per_team"              "2"
>                 "coaches_must_ready"            "0"
>                 "min_players_to_ready"          "2"
>                 "min_spectators_to_ready"               "0"
>                 "match_title"           "Match 2"
>                 "clinch_series"         "1"
>                 "wingman"               "0"
>                 "favored_percentage_team1"              "0"
>                 "side_type"             "standard"
>                 "maplist"
>                 {
>                         "de_dust2"              "__placeholder"
>                         "de_mirage"             "__placeholder"
>                 }
>                 "team1"
>                 {
>                         "players"
>                         {
>                                 "76561199473694121"             "asdasd"
>                         }
>                 }
>                 "team2"
>                 {
>                         "players"
>                         {
>                                 "76561199473694129"             "nyx2"
>                         }
>                 }
>                 "spectators"
>                 {
>                         "name"          "casters"
>                 }
>                 "cvars"
>                 {
>                         "mp_maxrounds"          "20"
>                         "mp_overtime_enable"            "0"
>                         "mp_match_can_clinch"           "0"
>                         "mp_match_restart_delay"                "30"
>                         "cash_team_loser_bonus"         "1900"
>                         "mp_consecutive_loss_max"               "3"
>                 }
>         }
>         "Stats"
>         {
>                 "series_type"           "bo2"
>                 "team1"
>                 {
>                 }
>                 "team2"
>                 {
>                 }
>         }
> }
> ```

okay... thanks for your reply.

do you think it could be related to the "fromfile" command?
because on my "normal" cfg that i use when we are not playing with 4 teams, cvars get executed as well  (on 14.4 and below as well)....

**Comment by nickdnk** [comment]
I used fromfile in team and map list and it worked correctly, as you can see. I don't know why it doesn't work for you.

**Comment by nickdnk** [comment]
Never mind last comment. I figured it out. It's only if:

1. You use KeyValues, not JSON
2. You use `veto_mode` and `cvars`
3. You don't have `skip_veto: true` **or** you have `maplist.length == num_maps` (which I had when testing).

I've fixed it with 0.14.7: https://github.com/splewis/get5/releases/tag/v0.14.7

**Comment by deLuXe83** [comment]
wow you‘re awesome!! thank you very much!
I will update and give feedback as soon as possible!

**Comment by deLuXe83** [comment]
Hi.

Still having issues on playing workshop maps :)

From time to time after one workshoip map is finished, it won't switch to next workshop map.
Manually change to e.g. dust2 is working. After that mapchange to workshop map works.

This console output:
`[Get5] The map will change once GOTV has finished broadcasting.
Completed GOTV demo "2023-06-08_23_252_map4_de_abbey.dem", recording time 2657.5
StopRecording: 3360 frames flushed in 2.33 seconds
Net channel ratelimit exceeded for 91.5.63.48:27005: 37 packets rejected.
Schakal: joschi was is mit den eiern?
[Get5] The map will change once GOTV has finished broadcasting.
[Get5] Changing map to de_DONOTBANPICK...
[Get5] The map will change once GOTV has finished broadcasting.
CHANGELEVEL: Looking for next level in mapgroup '1215935299'
Looking for next map in mapgroup '1215935299'...
CHANGELEVEL: Choosing map 'workshop/1215935299/de_abbey' (previous was workshop/1215935299/de_abbey)
CHANGELEVEL: Not changing level, mp_match_end_restart is false, mp_match_end_changelevel is false and next is the same
EVERYONE CAN BUY!`

'mp_match_end_restart' is set to '1' in cfg file.

Any ideas?

Bests!

**Comment by nickdnk** [comment]
What is `de_DONOTBANPICK` supposed to do?

I don't see any errors in the log, so I'm not sure what the log is supposed to highlight.

**Comment by deLuXe83** [comment]
> What is `de_DONOTBANPICK` supposed to do?
> 
> I don't see any errors in the log, so I'm not sure what the log is supposed to highlight.
> 
> It would also be helpful if you would create a new issue and fill out the template, including the match config, as this has nothing to do with invalid file ID.

thank you for your reply - done => https://github.com/splewis/get5/issues/1030
