### ISSUE TITLE
Loop when all players are ready :(

### ISSUE THREAD

**Issue by PoW3rKj** [splewis/get5#156]
### Expected behavior

Match starts when all the 10 players are ready

### Actual behavior

Loop in chat = "The match will begin in 60 seconds"
Loop in console = I didn't have the logs cuz it happened during a CW, but there were issues about missing or not up to date files in sprays directory"

### Steps to reproduce
- Plugin version: Lastest
- Sourcemod version: Lastest

**Comment by splewis** [comment]
"Latest" is not a version.

My guess is that this was before the fix in https://github.com/splewis/get5/commit/dfe76430783a80e93326540ff52dce8aa7fcbe8d though.

**Comment by splewis** [comment]
I'm closing since I believe it's a bug that was fixed, and there's no version given.

**Comment by EAbychkov** [comment]
Hello, unfortunately, this is not fixed! 
Latest Dev Build  (get5-341.zip) still has this bug.
Only reproduce when all 10 players take place, but this ruins the game (((

**Comment by splewis** [comment]
If you think there is a still a bug, then please open a new issue with more information. (match config, actual steps to reproduce, ...)
