### ISSUE TITLE
Loaded Bo3 instead of Bo1

### ISSUE THREAD

**Issue by gabrielfgularte** [splewis/get5#194]
### Expected behavior
Load 1 map for a Bo1.

### Actual behavior
Loaded a Bo3 and fired a `match_config_load_fail` event with reason: `Cannot play a series of 3 maps with a maplist of 1 maps`.

```
{
    "event": "match_config_load_fail",
    "params": {
        "reason": "Cannot play a series of 3 maps with a maplist of 1 maps"
    },
    "matchid": "1"
}
```

### Steps to reproduce
Configure the match.json like this:

```JSON
{
  "matchid":"1",
  "num_maps":1,
  "maplist":[
    "de_cache"
  ],
  "team1":{
    "name":"Time A",
    "flag":"BR",
    "players":[
      "XXXXXXXX1422509"
    ]
  },
  "team2":{
    "name":"Time B",
    "flag":"BR",
    "players":[
      "XXXXXXXX6611177"
    ]
  },
  "side_type":"always_knife",
  "skip_veto":true,
  "players_per_team":1,
  "min_players_to_ready":1
}
```

- Plugin version: 354 (https://ci.splewis.net/job/get5/354/artifact/builds/get5/get5-354.zip)
- Sourcemod version: 1.8 (https://sm.alliedmods.net/smdrop/1.8/sourcemod-1.8.0-git6027-linux.tar.gz)

**Comment by gabrielfgularte** [comment]
I think this is the same problem as described in #169. @splewis commented that was solved in #180, but the issue continues for me.

**Comment by splewis** [comment]
The fix I did there only affected the keyvalues (.cfg), 90ede072b9a8b224eebe0979bd33ac81cbc72fd3 should fix it for json files. 

Can you try build 357?

**Comment by gabrielfgularte** [comment]
Thank you! I'll try as soon as I can.

**Comment by gabrielfgularte** [comment]
@splewis I've tested build 357 but still not worked for me.

I think this issue may be related with this two codes:

https://github.com/splewis/get5/blob/master/scripting/get5/matchconfig.sp
```
  if (MaxMapsToPlay(g_MapsToWin) > g_MapPoolList.Length) {
    MatchConfigFail("Cannot play a series of %d maps with a maplist of %d maps",
                    MaxMapsToPlay(g_MapsToWin), g_MapPoolList.Length);
    return false;
  }
```

https://github.com/splewis/get5/blob/master/scripting/get5/util.sp
```
stock int MaxMapsToPlay(int mapsToWin) {
  if (g_BO2Match)
    return 2;
  else
    return 2 * mapsToWin - 1;
}
```

If `g_MapsToWin == 1`, then  `2 * mapsToWin - 1` is equal to 0, which makes `MaxMapsToPlay(g_MapsToWin) > g_MapPoolList.Length` true and the message `Cannot play a series of %d maps with a maplist of %d maps` is fired and the match config fails.

If we add an extra verification to `MaxMapsToPlay` for Bo1 matches this will be solved. Something like:
```
stock int MaxMapsToPlay(int mapsToWin) {
  if (g_BO2Match)
    return 2;
  else if mapsToWin == 1
    return 1
  else
    return 2 * mapsToWin - 1;
}
```

But I don't know if this is the best approach. What you think?

**Comment by splewis** [comment]
> If g_MapsToWin == 1, then 2 * mapsToWin - 1 will be 0,

Uh, isn't it 2 * 1 - 1 = 1?

When I tried to reproduce this, I failed. I'd suggest adding some LogMessage lines (or LogDebug if you have that enabled) around those lines and the global g_MapsToWin.

**Comment by gabrielfgularte** [comment]
>Uh, isn't it 2 * 1 - 1 = 1?

Damn you right. I don't know where were my head to get that result. I apologise.

I'm gonna add some log to debug and I'll come back with more details.

Thanks.

**Comment by gabrielfgularte** [comment]
So I guess I figured out what might be causing this problem. Your calculation is correct `2 * 1 - 1 = 1`. But in the `matchconfig.sp` code snippet, the comparison made is that` MaxMapsToPlay (g_MapsToWin) `is greater than` g_MapPoolList.Length` in that part of code here:

https://github.com/splewis/get5/blob/master/scripting/get5/matchconfig.sp
```
  if (MaxMapsToPlay(g_MapsToWin) > g_MapPoolList.Length) {
    MatchConfigFail("Cannot play a series of %d maps with a maplist of %d maps",
                    MaxMapsToPlay(g_MapsToWin), g_MapPoolList.Length);
    return false;
  }
```
Since `1> 1 = false`, this will always go into this if and raise the error.

Changing it to `if (MaxMapsToPlay(g_MapsToWin) != 1 && MaxMapsToPlay(g_MapsToWin) > g_MapPoolList.Length)` worked for me. If you like of this implementation I can make a PR. :)

**Comment by Technoblazed** [comment]
But, `1>1` would return false, so that if statement wouldn't be triggered anyway?

**Comment by gabrielfgularte** [comment]
@Technoblazed No, since `MaxMapsToPlay(g_MapsToWin) != 1` is `true`. :)

**Comment by Technoblazed** [comment]
You received this message, `Cannot play a series of 3 maps with a maplist of 1 maps` - The default fallback value for `num_maps` is 3, which must've been what triggered that, which means there's likely another issue somewhere here.

**Comment by gabrielfgularte** [comment]
@Technoblazed Yeah... You're right. But, this code have worked for me:

```
  if (MaxMapsToPlay(g_MapsToWin) != 1 && MaxMapsToPlay(g_MapsToWin) > g_MapPoolList.Length) {
    MatchConfigFail("Cannot play a series of %d maps with a maplist of %d maps",
                    MaxMapsToPlay(g_MapsToWin), g_MapPoolList.Length);
    return false;
  }
```

**Comment by Technoblazed** [comment]
That's because `MaxMapsToPlay(g_MapsToWin)` is 3.

**Comment by Technoblazed** [comment]
Right here, https://github.com/splewis/get5/blob/master/scripting/get5/matchconfig.sp#L484 could you stick a debug logger and get the value of numMaps

**Comment by gabrielfgularte** [comment]
@splewis and @Technoblazed this is not a bug at all. I was stupid enough to reload the server with the same old get5 versions over and over.

I think this was fixed in 90ede07 (build 357).

Thank you for your support and sorry for my lack of attention.

**Comment by Technoblazed** [comment]
I was trying to find what was causing it, good job it's fixed now though :^)

**Comment by gabrielfgularte** [comment]
Thank you! I'm closing it. :)
