### ISSUE TITLE
Match not always correctly ending and kicking players

### ISSUE THREAD

**Issue by potato20** [splewis/get5#89]
Problem: Match not always correctly ending

### Expected behavior

Expected players to get kicked, match to finish and apistats should send a final post request

### Actual behavior

Sometimes this works, some times it doesn't. I'm not sure why.

### Steps to reproduce
- Plugin version: 0.4.0
- metamod 1.10.6
- Sourcemod version: 1.8.0
- smjansson 2.3.1.3
- system2
- steamworks git121

steps:
- enable get_apistats by moving it out of disabled directory
- loadmatch_url the following json object:

```
{
  "matchid": "example_match",
  "match_title": "Map {MAPNUMBER} of {MAXMAPS}",
  "maps_to_win": 1,
  "players_per_team": 1,
  "skip_veto": true,
  "side_type": "never_knife",


  "maplist":
  [
    "workshop/122443683/aim_map.bsp",
    "workshop/192822991/aim_100hp.bsp",
    "workshop/152884032/aim_lowtreat.bsp",
    "workshop/192828439/aim_map_ruins_edit.bsp"
  ],

  "team1": {
    "name":"team1",
    "players":[
      "<redacted steam64 id>"
    ]
  },

  "team2": {
    "name":"team2",
    "players":[
      "<redacted steam64 id>"
    ]
  },

  "cvars": {
    "get5_web_api_url": "http://192.168.0.10:3000/",
    "get5_web_api_key": "abc123"
  }
};
```

- `get5_loadmatch remote.json`

- both players connect, play 1 map, and one player wins

i have a nodejs server running at 192.168.0.10:3000 catching all post requests from get5_apistats. when the plugin works correctly, i manage to see all post requests, and the players should get kicked with the message "The match has been finished". however, when this bug occurs, i only manage to get the very first request:

```
URL: http://192.168.0.10:3000/match/0/map/0/start
BODY: { key: 'abc123', mapname: 'workshop/122443683/aim_map' }
```

the nothing else afterwards. after one player wins, the server doesn't kick the players out. it lets them choose their team and they somehow continue playing (after the 2 minute pause time).

**Comment by Technoblazed** [comment]
Weird way of doing it, but pretty sure if you're using get5-web, the code changes when a match is made, if you have web, just use the web.

**Comment by potato20** [comment]
based on the tests/code in get5-web, all the get5 plugin requires is a 200 response, which is what my server is doing, so it shouldn't be an issue. i dont plan on using get5-web.

**Comment by potato20** [comment]
None of the calls to `SteamWorks_SendHTTPRequest` in the get5_apistats.sp do anything with the response so it's not like running get5-web is an issue. on the other hand, it's not really an apistats issue. even with the mod disabled, the match doesn't always kick people out.

**Comment by Technoblazed** [comment]
Have you configured your database correctly

**Comment by Technoblazed** [comment]
I.e ran the python script that actually creates the matches

**Comment by Technoblazed** [comment]
What am I talking about, too tired. Your API stats is going to send a request to get5-web, if the database has no match with your ID, well yeah

**Comment by potato20** [comment]
Yeah i was a little confused. On the node side, it doesn't do anything with the data. it just logs it and sends a 200 response. the get5_mysql plugin is disabled, so it shouldn't be an issue.

like i said, sometimes everything works normally and as expected. the match completes, it kicks the players, telling them "The match has been finished". other times, it won't kick the players, and they'll stay on the server and continue to play.

i may have confused you by bringing in the get_apistats aspect, but i don't believe thats the problem. in fact, i'll disable it and try again.

**Comment by potato20** [comment]
Hmm ok something interesting happened:

- i disabled get_apistats
- i played a 1v1 game, best of 1. when team1 won, the game didn't kick players.
- **without restarting the server** i ran the following commands:
  - `get5_endmatch`
  - `sm_kick @all` (kicks all players)
  - `get5_loadmatch remote.json`
- the players reconnected, both ready-ed up. as soon as the first round began, it kicked both players saying "The match has been finished."

**Comment by Technoblazed** [comment]
- error logs?
- MySQL stats and get5-web use two different schemas

**Comment by potato20** [comment]
here ya go

```
L 11/29/2016 - 12:03:37: SourceMod error session started
L 11/29/2016 - 12:03:37: Info (map "") (file "errors_20161129.log")
L 11/29/2016 - 12:03:37: Failed lookup of gEntList directly - Reverting to lookup via LevelShutdown
L 11/29/2016 - 12:03:37: Failed lookup of gEntList - Reverting to networkable entities only
L 11/29/2016 - 12:03:41: Error log file session closed.
L 11/29/2016 - 12:03:41: SourceMod error session started
L 11/29/2016 - 12:03:41: Info (map "de_dust") (file "errors_20161129.log")
L 11/29/2016 - 12:03:41: [SDKTOOLS] Invalid detour address passed - Disabling detour to prevent crashes
L 11/29/2016 - 12:03:52: Error log file session closed.
L 11/29/2016 - 12:04:27: SourceMod error session started
L 11/29/2016 - 12:04:27: Info (map "") (file "errors_20161129.log")
L 11/29/2016 - 12:04:27: Failed lookup of gEntList directly - Reverting to lookup via LevelShutdown
L 11/29/2016 - 12:04:27: Failed lookup of gEntList - Reverting to networkable entities only
L 11/29/2016 - 12:04:27: Error log file session closed.
L 11/29/2016 - 12:04:27: SourceMod error session started
L 11/29/2016 - 12:04:27: Info (map "de_dust") (file "errors_20161129.log")
L 11/29/2016 - 12:04:27: [SDKTOOLS] Invalid detour address passed - Disabling detour to prevent crashes
L 11/29/2016 - 12:04:29: Error log file session closed.
L 11/29/2016 - 12:10:28: SourceMod error session started
L 11/29/2016 - 12:10:28: Info (map "workshop/122443683/aim_map") (file "errors_20161129.log")
L 11/29/2016 - 12:10:28: [get5_apistats.smx] Failed to create logo directory
L 11/29/2016 - 12:10:31: Error log file session closed.
L 11/29/2016 - 12:15:33: SourceMod error session started
L 11/29/2016 - 12:15:33: Info (map "workshop/122443683/aim_map") (file "errors_20161129.log")
L 11/29/2016 - 12:15:33: [get5.smx] GOTV demo could not be recorded since tv_enable is not set to 1
L 11/29/2016 - 12:16:02: [SM] Exception reported: Failed to locate CheckWinLimit function
L 11/29/2016 - 12:16:02: [SM] Blaming: get5.smx
L 11/29/2016 - 12:16:02: [SM] Call stack trace:
L 11/29/2016 - 12:16:02: [SM]   [0] CS_GetTeamScore
L 11/29/2016 - 12:16:02: [SM]   [1] Line 1132, ./scripting/get5.sp::Event_RoundEnd
L 11/29/2016 - 12:16:15: [SM] Exception reported: Failed to locate CheckWinLimit function
L 11/29/2016 - 12:16:15: [SM] Blaming: get5.smx
L 11/29/2016 - 12:16:15: [SM] Call stack trace:
L 11/29/2016 - 12:16:15: [SM]   [0] CS_GetTeamScore
L 11/29/2016 - 12:16:15: [SM]   [1] Line 1132, ./scripting/get5.sp::Event_RoundEnd
L 11/29/2016 - 12:16:26: [SM] Exception reported: Failed to locate CheckWinLimit function
L 11/29/2016 - 12:16:26: [SM] Blaming: get5.smx
L 11/29/2016 - 12:16:26: [SM] Call stack trace:
L 11/29/2016 - 12:16:26: [SM]   [0] CS_GetTeamScore
L 11/29/2016 - 12:16:26: [SM]   [1] Line 1132, ./scripting/get5.sp::Event_RoundEnd
L 11/29/2016 - 12:16:26: [SM] Exception reported: Failed to locate CheckWinLimit function
L 11/29/2016 - 12:16:26: [SM] Blaming: get5.smx
L 11/29/2016 - 12:16:26: [SM] Call stack trace:
L 11/29/2016 - 12:16:26: [SM]   [0] CS_GetTeamScore
L 11/29/2016 - 12:16:26: [SM]   [1] Line 911, ./scripting/get5.sp::Event_MatchOver
L 11/29/2016 - 12:23:12: SourceMod error session started
L 11/29/2016 - 12:23:12: Info (map "workshop/122443683/aim_map") (file "errors_20161129.log")
L 11/29/2016 - 12:23:12: [get5_apistats.smx] Failed to create logo directory
L 11/29/2016 - 12:23:15: Error log file session closed.
L 11/29/2016 - 12:24:02: SourceMod error session started
L 11/29/2016 - 12:24:02: Info (map "workshop/122443683/aim_map") (file "errors_20161129.log")
L 11/29/2016 - 12:24:02: [get5.smx] GOTV demo could not be recorded since tv_enable is not set to 1
L 11/29/2016 - 12:27:47: [get5_apistats.smx] Failed to create logo directory
L 11/29/2016 - 12:27:50: Error log file session closed.
L 11/29/2016 - 12:28:14: SourceMod error session started
L 11/29/2016 - 12:28:14: Info (map "workshop/122443683/aim_map") (file "errors_20161129.log")
L 11/29/2016 - 12:28:14: [get5.smx] GOTV demo could not be recorded since tv_enable is not set to 1
L 11/29/2016 - 12:30:15: [SM] Exception reported: Invalid index 2 (count: 1)
L 11/29/2016 - 12:30:15: [SM] Blaming: get5.smx
L 11/29/2016 - 12:30:15: [SM] Call stack trace:
L 11/29/2016 - 12:30:15: [SM]   [0] ArrayList.GetString
L 11/29/2016 - 12:30:15: [SM]   [1] Line 969, ./scripting/get5.sp::Event_MatchOver
L 11/29/2016 - 12:31:18: [SM] Exception reported: Invalid Handle 0 (error: 4)
L 11/29/2016 - 12:31:18: [SM] Blaming: get5.smx
L 11/29/2016 - 12:31:18: [SM] Call stack trace:
L 11/29/2016 - 12:31:18: [SM]   [0] GetArrayCell
L 11/29/2016 - 12:31:18: [SM]   [1] Line 31, ./scripting/include/restorecvars.inc::RestoreCvars
L 11/29/2016 - 12:31:18: [SM]   [2] Line 1041, ./scripting/get5.sp::EndSeries
L 11/29/2016 - 12:31:18: [SM]   [4] Call_Finish
L 11/29/2016 - 12:31:18: [SM]   [5] Line 612, ./scripting/get5/util.sp::_DelayFunctionCallback
L 11/29/2016 - 14:17:27: SourceMod error session started
L 11/29/2016 - 14:17:27: Info (map "workshop/122443683/aim_map") (file "errors_20161129.log")
L 11/29/2016 - 14:17:27: [get5.smx] GOTV demo could not be recorded since tv_enable is not set to 1
L 11/29/2016 - 14:19:32: Error log file session closed.
L 11/29/2016 - 14:20:05: SourceMod error session started
L 11/29/2016 - 14:20:05: Info (map "workshop/122443683/aim_map") (file "errors_20161129.log")
L 11/29/2016 - 14:20:05: [get5.smx] GOTV demo could not be recorded since tv_enable is not set to 1
L 11/29/2016 - 14:20:46: Error log file session closed.
L 11/29/2016 - 14:21:03: SourceMod error session started
L 11/29/2016 - 14:21:03: Info (map "workshop/122443683/aim_map") (file "errors_20161129.log")
L 11/29/2016 - 14:21:03: [get5.smx] GOTV demo could not be recorded since tv_enable is not set to 1
L 11/29/2016 - 14:23:22: Error log file session closed.
L 11/29/2016 - 14:23:48: SourceMod error session started
L 11/29/2016 - 14:23:48: Info (map "workshop/122443683/aim_map") (file "errors_20161129.log")
L 11/29/2016 - 14:23:48: [get5.smx] GOTV demo could not be recorded since tv_enable is not set to 1
```

**Comment by Technoblazed** [comment]
- Pastebin/gist is a thing :^)
- API key changes for each map with get5-web, fair enough you have apistats enabled, but it wont work, if the api key does not match the other end, to which you have no other end.

**Comment by potato20** [comment]
>API key changes for each map with get5-web, fair enough you have apistats enabled, but it wont work, if the api key does not match the other end, to which you have no other end.

ok but you're missing the point. i regret even bringing this up. i disabled apistats entirely. can we forget about it? the issue is get5 not properly ending a match for some reason.

**Comment by Technoblazed** [comment]
```
[SDKTOOLS] Invalid detour address passed - Disabling detour to prevent crashes
```
=> Missing gamedata

**Comment by potato20** [comment]
I might have found an issue

https://github.com/splewis/get5/blob/b33b44a298abfde5db499586cb53bb4c8b95b225/scripting/get5.sp#L838

seems like it waits 10 seconds until it kicks players. I'm actually setting `mp_match_restart_delay` to 3 seconds. i'll see what'll happen if i actually let it wait 10 seconds.

**Comment by potato20** [comment]
Ok seems like if i let it do its thing without `mp_match_restart_delay`, it works ok.. gonna need more testing though, so i won't close this just yet.

**Comment by splewis** [comment]
I would suggest updating sourcemod and redoing any test. Your error logs have lots of errors caused by the 2016/11/28 update and would need updated gamedata to be fixed.

**Comment by Technoblazed** [comment]
Resolved in latest commits?

**Comment by potato20** [comment]
@Technoblazed will try later and let you know.

**Comment by potato20** [comment]
After doing a fresh csgo server install, installing the latest get5 from git and updating sourcemod to 5963, it still doesn't kick the players at the end of a match. Will do some more testing though.

**Comment by potato20** [comment]
Ok did some testing and found something. It's related to #95. It seems like if that log file exists and if get5 is logging to it, then it consistently kick players out of matches when the series end.

**Comment by Technoblazed** [comment]
@potato20, this fixed now too?

**Comment by potato20** [comment]
It seems to be ;)

**Comment by potato20** [comment]
It's your call to close the issue. Things seem to be working reliably on my end so far.

**Comment by splewis** [comment]
Sounds like it's fixed to me.

Reopen if you think there's a bug still.
